site:
  - name: !join ["拷", "贝", "漫", "画"]
    origin: !join &origin0 ["https", "://copym", "anga", ".net"]
    inject: "inject_copym.js"
    action:
      search:
        url: !join [*origin0, "/search?q={keyword}"]
        js_init: "return search_init({page_num})"
        js_result: "return search_result({page_num})"
      comic:
        js_init: "return comic_init()"
        js_result: "return comic_result()"
      chapter:
        js_init: "return chapter_init()"
        js_result: "return chapter_result()"
  - name: !join ["动", "漫", "之", "家"]
    origin: !join &origin1 ["https", "://m.dm", "zj", ".com"]
    inject: "inject_m_dm.js"
    action:
      search:
        url: !join [*origin1, "/search/{keyword}.html"]
        js_init: "return search_init({page_num})"
        js_result: "return search_result({page_num})"
      comic:
        js_init: "return comic_init()"
        js_result: "return comic_result()"
      chapter:
        js_init: "return chapter_init()"
        js_result: "return chapter_result()"